src/AppBundle/Entity/Cart.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Carts
 *
 * @ORM\Table(name="carts", indexes={@ORM\Index(name="id", columns={"id"}), @ORM\Index(name="user_id", columns={"user_id"}), @ORM\Index(name="user_id_2", columns={"user_id"})})
 * @ORM\Entity
 */
class Cart
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="user_id", type="integer", nullable=true)
     */
    private $userId;

    /**
     * @var \AppBundle\Entity\CartItem[]
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\CartItem", mappedBy="cart")
     */
    private $cartItems = [];

    /**
     * @var \AppBundle\Entity\Order
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Order", mappedBy="cart")
     */
    private $order;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set userId
     *
     * @param integer $userId
     *
     * @return Cart
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * Get userId
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * @return CartItem[]
     */
    public function getCartItems()
    {
        return $this->cartItems;
    }

    /**
     * @param CartItem[] $cartItems
     * @return Cart
     */
    public function setCartItems($cartItems)
    {
        $this->cartItems = $cartItems;

        return $this;
    }

    public function getTotalPrice()
    {
        $total = 0;
        foreach ($this->getCartItems() as $cartItem){
            $total+=$cartItem->getPrice()*$cartItem->getQuantity();
        }

        return $total;
    }

    /**
     * @return Order
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * @param Order $order
     * @return Cart
     */
    public function setOrder($order)
    {
        $this->order = $order;
        return $this;
    }


}

src/AppBundle/Entity/OrderItem.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * OrderItems
 *
 * @ORM\Table(name="order_items", indexes={@ORM\Index(name="part_id", columns={"part_id"}), @ORM\Index(name="id", columns={"id"}), @ORM\Index(name="part_id_2", columns={"part_id"}), @ORM\Index(name="part_id_3", columns={"part_id"}), @ORM\Index(name="order_id", columns={"order_id"})})
 * @ORM\Entity
 */
class OrderItem
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float", precision=10, scale=0, nullable=false)
     */
    private $price;

    /**
     * @var integer
     *
     * @ORM\Column(name="quantity", type="integer", nullable=false)
     */
    private $quantity;

    /**
     * @var \AppBundle\Entity\Order
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Order", inversedBy="orderItems")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="order_id", referencedColumnName="id")
     * })
     */
    private $order;

    /**
     * @var \AppBundle\Entity\Part
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Part")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="part_id", referencedColumnName="id")
     * })
     */
    private $part;


    public function __toString()
    {
        return $this->getPart()->getName().' '.$this->getQuantity();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set price
     *
     * @param float $price
     *
     * @return OrderItem
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     *
     * @return OrderItem
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set order_item
     *
     * @param \AppBundle\Entity\Order $order
     *
     * @return OrderItem
     */
    public function setOrder(\AppBundle\Entity\Order $order = null)
    {
        //$order->getOrderItems()[]=$this;
        $this->order = $order;

        return $this;
    }

    /**
     * Get order_item
     *
     * @return \AppBundle\Entity\Order
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Set part
     *
     * @param \AppBundle\Entity\Part $part
     *
     * @return OrderItem
     */
    public function setPart(\AppBundle\Entity\Part $part = null)
    {
        $this->part = $part;

        return $this;
    }

    /**
     * Get part
     *
     * @return \AppBundle\Entity\Part
     */
    public function getPart()
    {
        return $this->part;
    }
}

src/AppBundle/Controller/OrderItemController.php
<?php
/**
 * Created by PhpStorm.
 * User: Vio
 * Date: 23-02-2019
 * Time: 1:51 PM
 */

namespace AppBundle\Controller;


use AppBundle\Entity\Cart;
use AppBundle\Entity\Delivery;
use AppBundle\Entity\Order;
use AppBundle\Entity\OrderItem;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class OrderItemController extends Controller
{
    /**
     * @return Order
     */
    private function getOrder()
    {
        $em = $this->getDoctrine()->getManager();
        $session = $this->get('session');
        $cart = $em->getRepository(Cart::class)->find($session->get('cart_id'));
        $order = new Order();
        $order->setCart($cart);
        $order->setStatus('pending');
        $order->setUser($this->getUser());
        $em->persist($order);
        $em->flush();

        return $order;
    }

    private function addOrderItems(Order $order){
        $em = $this->getDoctrine()->getManager();
        $session = $this->get('session');

        /* @var Cart $cart
         * @var OrderItem $orderItem
         */

        $cart = $em->getRepository(Cart::class)->find($session->get('cart_id'));
        $coll = [];
        foreach ($cart->getCartItems() as $cartItem){
            $orderItem = new OrderItem();
            $orderItem->setQuantity($cartItem->getQuantity());
            $orderItem->setPrice($cartItem->getPrice());
            $orderItem->setPart($cartItem->getPart());
            $orderItem->setOrder($order);
            $em->persist($orderItem);
            $em->flush();
            $coll[]=$orderItem;
        }

        $order->setOrderItems($coll);

    }

    /**
     * @return Delivery
     */
    public function addDelivery(Request $request, $order){
        $em=$this->getDoctrine()->getManager();
        $delivery = new Delivery();
        $delivery->setName($request->get('name'));
        $delivery->setSurname($request->get('surname'));
        $delivery->setAddress($request->get('address'));
        $delivery->setTelephone($request->get('telephone'));
        $delivery->setOrder($order);
        $em->persist($delivery);
        $em->flush();

        return $delivery;
    }


    /**
     * @Route("/showOrder", name="showOrder")
     * @Template
     */
    public function showAction(Request $request){
        $order = $this->getOrder();
        $this->addOrderItems($order);
        $delivery = $this->addDelivery($request,$order);

        return[
            'order'=>$order,
            'userLogIn'=>ucfirst($this->container->get('security.token_storage')->getToken()->getUser()->getUserName()),
            'delivery'=>$delivery,
            ];

    }

}

src/AppBundle/Resources/views/order_item/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Cart items
{% endblock %}
{% block body %}
    {{ include('includes/navbar.html.twig') }}
    <br>
    <br>
    <br>
    <div style="margin-left: 10px">
    <h5> The command was successfully registered </h5>
    <br>
    The parts added are the following:
    <ul id="navigation">
        {% if array.message is defined %}
            <h3 style="color: red">{{ message }}</h3>
        {% else %}
            {% for orderItem in order.OrderItems %}
                <li>You bought {{ orderItem.part.name }}.. X ..{{ orderItem.price }} lei---- {{ orderItem.quantity }} -
                    pieces
                </li>

            {% endfor %}
        {% endif %}

    </ul>
    <h6 style="color: red">Total amount: {{ order.cart.totalPrice }} USD</h6>
    <h5> Formular de livrare </h5>
    </div>
    <div style="margin-left: 20px">
        <table>
            <tr>
                <th>
                    First name:
                </th>
                <td style="width: 500px" height="50">
                    {{ delivery.name }}
                </td>

            </tr>
            <tr>
                <th>
                    Last name:
                </th>
                <td style="width: 500px" height="50">
                    {{ delivery.surname }}
                </td>
            </tr>
            <tr>
                <th>
                    Address:
                </th>
                <td style="width: 500px" height="50">
                    {{ delivery.address }}
                </td>
            </tr>
            <tr>
                <th>
                    Phone number:
                </th>
                <td style="width: 500px" height="50">
                    {{ delivery.telephone }}
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td>

                    <form action="{{ url('showInvoice',{ "orderId":order.id, "action":"I"}) }}">
                        <input name="viewInvoice" type="submit" value="Preview invoice" >
                    </form>
                </td>
                <td>
                    <form action="{{ url('showInvoice',{ "orderId":order.id, "action":"D"}) }}">
                        <input name="viewInvoice" type="submit" value="Download invoice" >
                    </form>
                </td>
            </tr>
        </table>

        <h6><a href="{{ url('manufacturers') }}">Back to manufacturers</a></h6>
        {{ include('includes/footer.html.twig') }}
    </div>

{% endblock %}